# Navigation Links
#   The weight parameter defines the order that the links will appear in (lower = further left).

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about/
    weight: 20
  - name: Publications
    url: /papers
    weight: 30
  - name: Presentations
    url: /talks
    weight: 40
  - name: Skills
    url: /skills
    weight: 50
  - name: Experience
    url: experience/
    weight: 60
  - name: Projects
    url: projects/
    weight: 70
  - name: Teaching
    url: teaching/
    weight: 80
